---
# create Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: cloudns
spec:
  selector:
    matchLabels:
      app: fastapi-app
  replicas: 3
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: py-app
          image: glebcom/py-app
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: local
              containerPort: 8000
              protocol: TCP
          env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: AUTHOR
              # value: "Gleb K."
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: author
          livenessProbe:
            httpGet:
              port: local
              path: /liveness
            initialDelaySeconds: 5
            periodSeconds: 25
          readinessProbe:
            httpGet:
              port: local
              path: /readiness
            initialDelaySeconds: 5
            periodSeconds: 3
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: config-map

---
# create ClusterIP Service

apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: cloudns
spec:
  type: ClusterIP
  selector:
    app: fastapi-app
  ports:
    - port: 80
      targetPort: local
      protocol: TCP
